// <auto-generated />
using System;
using InvestFlowCaixa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestFlowCaixa.Infrastructure.Migrations
{
    [DbContext(typeof(InvestimentosDbContext))]
    [Migration("20251117203219_SeedProdutosInvestimentoTwo")]
    partial class SeedProdutosInvestimentoTwo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FrequenciaMovimentacoes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PreferenciaLiquidez")
                        .HasColumnType("int");

                    b.Property<int>("PreferenciaRentabilidade")
                        .HasColumnType("int");

                    b.Property<decimal>("RendaMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<decimal>("VolumeInvestimentos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.HistoricoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rentabilidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("HistoricoInvestimentos", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.PerfilRisco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PerfisRisco", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Baixa movimentação e foco em liquidez.",
                            Nome = "Conservador"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Equilíbrio entre liquidez e rentabilidade.",
                            Nome = "Moderado"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Busca por alta rentabilidade assumindo maior risco.",
                            Nome = "Agressivo"
                        });
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.ProdutoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Liquidez")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaxPrazoMeses")
                        .HasColumnType("int");

                    b.Property<decimal>("MinValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Rentabilidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProdutosInvestimento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 24,
                            MinValor = 1000m,
                            Nome = "CDB Banco Caixa",
                            Rentabilidade = 0.1125m,
                            Risco = "Baixo",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 2,
                            Liquidez = "D+90",
                            MaxPrazoMeses = 36,
                            MinValor = 5000m,
                            Nome = "LCI Caixa Imobiliário",
                            Rentabilidade = 0.092m,
                            Risco = "Baixo",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 3,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 48,
                            MinValor = 50m,
                            Nome = "Tesouro Selic 2027",
                            Rentabilidade = 0.1035m,
                            Risco = "Baixo",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 4,
                            Liquidez = "D+15",
                            MaxPrazoMeses = 36,
                            MinValor = 2000m,
                            Nome = "CDB Caixa Performance",
                            Rentabilidade = 0.132m,
                            Risco = "Moderado",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 5,
                            Liquidez = "D+120",
                            MaxPrazoMeses = 48,
                            MinValor = 7000m,
                            Nome = "LCI Caixa Desenvolvimento",
                            Rentabilidade = 0.115m,
                            Risco = "Moderado",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 6,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 60,
                            MinValor = 100m,
                            Nome = "Tesouro Prefixado 2029",
                            Rentabilidade = 0.145m,
                            Risco = "Moderado",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 7,
                            Liquidez = "D+30",
                            MaxPrazoMeses = 60,
                            MinValor = 1000m,
                            Nome = "CDB Retorno Turbo XPTO",
                            Rentabilidade = 0.165m,
                            Risco = "Alto",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 8,
                            Liquidez = "D+180",
                            MaxPrazoMeses = 72,
                            MinValor = 8000m,
                            Nome = "LCI FlexMax Corporativa",
                            Rentabilidade = 0.152m,
                            Risco = "Alto",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 9,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 120,
                            MinValor = 100m,
                            Nome = "Tesouro Prefixado 2035 Alta Volatilidade",
                            Rentabilidade = 0.185m,
                            Risco = "Alto",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 10,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 36,
                            MinValor = 2000m,
                            Nome = "CDB Caixa Estabilidade",
                            Rentabilidade = 0.118m,
                            Risco = "Baixo",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 11,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 48,
                            MinValor = 3000m,
                            Nome = "CDB Caixa Conservador Plus",
                            Rentabilidade = 0.121m,
                            Risco = "Baixo",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 12,
                            Liquidez = "D+120",
                            MaxPrazoMeses = 48,
                            MinValor = 6000m,
                            Nome = "LCI Caixa Habitação Popular",
                            Rentabilidade = 0.097m,
                            Risco = "Baixo",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 13,
                            Liquidez = "D+180",
                            MaxPrazoMeses = 60,
                            MinValor = 8000m,
                            Nome = "LCI Caixa Infraestrutura Residencial",
                            Rentabilidade = 0.101m,
                            Risco = "Baixo",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 14,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 60,
                            MinValor = 100m,
                            Nome = "Tesouro Selic 2029",
                            Rentabilidade = 0.108m,
                            Risco = "Baixo",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 15,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 72,
                            MinValor = 200m,
                            Nome = "Tesouro Selic 2031",
                            Rentabilidade = 0.112m,
                            Risco = "Baixo",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 16,
                            Liquidez = "D+30",
                            MaxPrazoMeses = 48,
                            MinValor = 3000m,
                            Nome = "CDB Caixa Dinâmico",
                            Rentabilidade = 0.138m,
                            Risco = "Moderado",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 17,
                            Liquidez = "D+60",
                            MaxPrazoMeses = 60,
                            MinValor = 4000m,
                            Nome = "CDB Caixa Evolução",
                            Rentabilidade = 0.143m,
                            Risco = "Moderado",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 18,
                            Liquidez = "D+150",
                            MaxPrazoMeses = 60,
                            MinValor = 9000m,
                            Nome = "LCI Caixa Corporativa",
                            Rentabilidade = 0.123m,
                            Risco = "Moderado",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 19,
                            Liquidez = "D+180",
                            MaxPrazoMeses = 72,
                            MinValor = 12000m,
                            Nome = "LCI Caixa Premium",
                            Rentabilidade = 0.129m,
                            Risco = "Moderado",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 20,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 72,
                            MinValor = 150m,
                            Nome = "Tesouro Prefixado 2031",
                            Rentabilidade = 0.152m,
                            Risco = "Moderado",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 21,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 96,
                            MinValor = 200m,
                            Nome = "Tesouro IPCA+ 2035 Moderado",
                            Rentabilidade = 0.158m,
                            Risco = "Moderado",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 22,
                            Liquidez = "D+45",
                            MaxPrazoMeses = 72,
                            MinValor = 2000m,
                            Nome = "CDB Potencial Max",
                            Rentabilidade = 0.175m,
                            Risco = "Alto",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 23,
                            Liquidez = "D+90",
                            MaxPrazoMeses = 96,
                            MinValor = 4000m,
                            Nome = "CDB Renda Turbo",
                            Rentabilidade = 0.188m,
                            Risco = "Alto",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 24,
                            Liquidez = "D+240",
                            MaxPrazoMeses = 84,
                            MinValor = 10000m,
                            Nome = "LCI Caixa MaxInvest",
                            Rentabilidade = 0.163m,
                            Risco = "Alto",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 25,
                            Liquidez = "D+360",
                            MaxPrazoMeses = 96,
                            MinValor = 15000m,
                            Nome = "LCI Caixa HighYield",
                            Rentabilidade = 0.172m,
                            Risco = "Alto",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 26,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 144,
                            MinValor = 200m,
                            Nome = "Tesouro Prefixado 2040 HighVol",
                            Rentabilidade = 0.198m,
                            Risco = "Alto",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 27,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 180,
                            MinValor = 500m,
                            Nome = "Tesouro IPCA+ 2045 HighRisk",
                            Rentabilidade = 0.215m,
                            Risco = "Alto",
                            Tipo = "Tesouro"
                        });
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoInvestimentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentabilidadeEfetiva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInvestido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoInvestimentoId");

                    b.HasIndex("ClienteId", "DataSimulacao");

                    b.ToTable("Simulacoes", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.TelemetriaServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantidadeChamadas")
                        .HasColumnType("int");

                    b.Property<int>("TempoMedioRespostaMs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomeServico");

                    b.ToTable("TelemetriaServicos", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("InvestFlowCaixa.Domain.Entities.PerfilRisco", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.HistoricoInvestimento", b =>
                {
                    b.HasOne("InvestFlowCaixa.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Historico")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Simulacao", b =>
                {
                    b.HasOne("InvestFlowCaixa.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Simulacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestFlowCaixa.Domain.Entities.ProdutoInvestimento", "ProdutoInvestimento")
                        .WithMany()
                        .HasForeignKey("ProdutoInvestimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ProdutoInvestimento");
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("Simulacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
