// <auto-generated />
using System;
using InvestFlowCaixa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestFlowCaixa.Infrastructure.Migrations
{
    [DbContext(typeof(InvestimentosDbContext))]
    [Migration("20251121123722_AddSimulacoesSeed")]
    partial class AddSimulacoesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FrequenciaMovimentacoes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PreferenciaLiquidez")
                        .HasColumnType("int");

                    b.Property<int>("PreferenciaRentabilidade")
                        .HasColumnType("int");

                    b.Property<decimal>("RendaMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VolumeInvestimentos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CPF = "11111111111",
                            FrequenciaMovimentacoes = 3,
                            Nome = "Cliente Perfil Conservador",
                            PerfilId = 1,
                            PreferenciaLiquidez = 9,
                            PreferenciaRentabilidade = 2,
                            RendaMensal = 5000m,
                            Score = 0,
                            SenhaHash = new byte[] { 114, 59, 225, 255, 209, 23, 103, 84, 80, 201, 10, 56, 25, 181, 239, 206, 115, 91, 189, 115, 178, 202, 147, 195, 250, 29, 93, 200, 44, 199, 64, 145, 247, 17, 209, 2, 91, 208, 142, 139, 29, 221, 85, 116, 175, 36, 204, 133, 0, 119, 145, 78, 156, 27, 51, 247, 42, 77, 239, 254, 13, 75, 241, 108 },
                            SenhaSalt = new byte[] { 213, 205, 22, 48, 214, 249, 142, 176, 133, 141, 2, 132, 150, 238, 86, 62, 145, 217, 220, 152, 254, 104, 59, 136, 95, 99, 64, 10, 39, 199, 75, 109, 145, 88, 133, 240, 62, 186, 141, 61, 224, 36, 228, 6, 185, 87, 178, 213, 57, 71, 49, 15, 143, 114, 216, 144, 16, 161, 177, 138, 133, 8, 73, 134, 255, 88, 101, 51, 84, 216, 171, 144, 199, 252, 194, 1, 61, 125, 253, 136, 161, 88, 167, 25, 170, 97, 92, 14, 204, 109, 17, 211, 209, 1, 152, 60, 239, 76, 16, 170, 153, 221, 22, 209, 13, 106, 235, 154, 188, 172, 202, 85, 123, 209, 93, 171, 191, 42, 224, 202, 76, 128, 137, 189, 251, 228, 167, 54 },
                            Token = "",
                            VolumeInvestimentos = 20000m
                        },
                        new
                        {
                            Id = 102,
                            CPF = "22222222222",
                            FrequenciaMovimentacoes = 10,
                            Nome = "Cliente Perfil Moderado",
                            PerfilId = 2,
                            PreferenciaLiquidez = 5,
                            PreferenciaRentabilidade = 5,
                            RendaMensal = 8000m,
                            Score = 0,
                            SenhaHash = new byte[] { 114, 59, 225, 255, 209, 23, 103, 84, 80, 201, 10, 56, 25, 181, 239, 206, 115, 91, 189, 115, 178, 202, 147, 195, 250, 29, 93, 200, 44, 199, 64, 145, 247, 17, 209, 2, 91, 208, 142, 139, 29, 221, 85, 116, 175, 36, 204, 133, 0, 119, 145, 78, 156, 27, 51, 247, 42, 77, 239, 254, 13, 75, 241, 108 },
                            SenhaSalt = new byte[] { 213, 205, 22, 48, 214, 249, 142, 176, 133, 141, 2, 132, 150, 238, 86, 62, 145, 217, 220, 152, 254, 104, 59, 136, 95, 99, 64, 10, 39, 199, 75, 109, 145, 88, 133, 240, 62, 186, 141, 61, 224, 36, 228, 6, 185, 87, 178, 213, 57, 71, 49, 15, 143, 114, 216, 144, 16, 161, 177, 138, 133, 8, 73, 134, 255, 88, 101, 51, 84, 216, 171, 144, 199, 252, 194, 1, 61, 125, 253, 136, 161, 88, 167, 25, 170, 97, 92, 14, 204, 109, 17, 211, 209, 1, 152, 60, 239, 76, 16, 170, 153, 221, 22, 209, 13, 106, 235, 154, 188, 172, 202, 85, 123, 209, 93, 171, 191, 42, 224, 202, 76, 128, 137, 189, 251, 228, 167, 54 },
                            Token = "",
                            VolumeInvestimentos = 50000m
                        },
                        new
                        {
                            Id = 103,
                            CPF = "33333333333",
                            FrequenciaMovimentacoes = 30,
                            Nome = "Cliente Perfil Agressivo",
                            PerfilId = 3,
                            PreferenciaLiquidez = 1,
                            PreferenciaRentabilidade = 9,
                            RendaMensal = 15000m,
                            Score = 0,
                            SenhaHash = new byte[] { 114, 59, 225, 255, 209, 23, 103, 84, 80, 201, 10, 56, 25, 181, 239, 206, 115, 91, 189, 115, 178, 202, 147, 195, 250, 29, 93, 200, 44, 199, 64, 145, 247, 17, 209, 2, 91, 208, 142, 139, 29, 221, 85, 116, 175, 36, 204, 133, 0, 119, 145, 78, 156, 27, 51, 247, 42, 77, 239, 254, 13, 75, 241, 108 },
                            SenhaSalt = new byte[] { 213, 205, 22, 48, 214, 249, 142, 176, 133, 141, 2, 132, 150, 238, 86, 62, 145, 217, 220, 152, 254, 104, 59, 136, 95, 99, 64, 10, 39, 199, 75, 109, 145, 88, 133, 240, 62, 186, 141, 61, 224, 36, 228, 6, 185, 87, 178, 213, 57, 71, 49, 15, 143, 114, 216, 144, 16, 161, 177, 138, 133, 8, 73, 134, 255, 88, 101, 51, 84, 216, 171, 144, 199, 252, 194, 1, 61, 125, 253, 136, 161, 88, 167, 25, 170, 97, 92, 14, 204, 109, 17, 211, 209, 1, 152, 60, 239, 76, 16, 170, 153, 221, 22, 209, 13, 106, 235, 154, 188, 172, 202, 85, 123, 209, 93, 171, 191, 42, 224, 202, 76, 128, 137, 189, 251, 228, 167, 54 },
                            Token = "",
                            VolumeInvestimentos = 150000m
                        });
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.HistoricoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rentabilidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("HistoricoInvestimentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            ClienteId = 101,
                            Data = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1125m,
                            Tipo = "CDB",
                            Valor = 1000m
                        },
                        new
                        {
                            Id = 1002,
                            ClienteId = 101,
                            Data = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1180m,
                            Tipo = "CDB",
                            Valor = 2000m
                        },
                        new
                        {
                            Id = 1003,
                            ClienteId = 101,
                            Data = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1210m,
                            Tipo = "CDB",
                            Valor = 3000m
                        },
                        new
                        {
                            Id = 1004,
                            ClienteId = 101,
                            Data = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.0920m,
                            Tipo = "LCI",
                            Valor = 5000m
                        },
                        new
                        {
                            Id = 1005,
                            ClienteId = 101,
                            Data = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.0970m,
                            Tipo = "LCI",
                            Valor = 6000m
                        },
                        new
                        {
                            Id = 1006,
                            ClienteId = 101,
                            Data = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1010m,
                            Tipo = "LCI",
                            Valor = 8000m
                        },
                        new
                        {
                            Id = 1007,
                            ClienteId = 101,
                            Data = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1035m,
                            Tipo = "Tesouro",
                            Valor = 50m
                        },
                        new
                        {
                            Id = 1008,
                            ClienteId = 101,
                            Data = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1080m,
                            Tipo = "Tesouro",
                            Valor = 100m
                        },
                        new
                        {
                            Id = 1009,
                            ClienteId = 101,
                            Data = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1120m,
                            Tipo = "Tesouro",
                            Valor = 200m
                        },
                        new
                        {
                            Id = 1010,
                            ClienteId = 102,
                            Data = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1320m,
                            Tipo = "CDB",
                            Valor = 2000m
                        },
                        new
                        {
                            Id = 1011,
                            ClienteId = 102,
                            Data = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1380m,
                            Tipo = "CDB",
                            Valor = 3000m
                        },
                        new
                        {
                            Id = 1012,
                            ClienteId = 102,
                            Data = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1430m,
                            Tipo = "CDB",
                            Valor = 4000m
                        },
                        new
                        {
                            Id = 1013,
                            ClienteId = 102,
                            Data = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1150m,
                            Tipo = "LCI",
                            Valor = 7000m
                        },
                        new
                        {
                            Id = 1014,
                            ClienteId = 102,
                            Data = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1230m,
                            Tipo = "LCI",
                            Valor = 9000m
                        },
                        new
                        {
                            Id = 1015,
                            ClienteId = 102,
                            Data = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1290m,
                            Tipo = "LCI",
                            Valor = 12000m
                        },
                        new
                        {
                            Id = 1016,
                            ClienteId = 102,
                            Data = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1450m,
                            Tipo = "Tesouro",
                            Valor = 100m
                        },
                        new
                        {
                            Id = 1017,
                            ClienteId = 102,
                            Data = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1520m,
                            Tipo = "Tesouro",
                            Valor = 150m
                        },
                        new
                        {
                            Id = 1018,
                            ClienteId = 102,
                            Data = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1580m,
                            Tipo = "Tesouro",
                            Valor = 200m
                        },
                        new
                        {
                            Id = 1019,
                            ClienteId = 103,
                            Data = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1650m,
                            Tipo = "CDB",
                            Valor = 1000m
                        },
                        new
                        {
                            Id = 1020,
                            ClienteId = 103,
                            Data = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1750m,
                            Tipo = "CDB",
                            Valor = 2000m
                        },
                        new
                        {
                            Id = 1021,
                            ClienteId = 103,
                            Data = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1880m,
                            Tipo = "CDB",
                            Valor = 4000m
                        },
                        new
                        {
                            Id = 1022,
                            ClienteId = 103,
                            Data = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1520m,
                            Tipo = "LCI",
                            Valor = 8000m
                        },
                        new
                        {
                            Id = 1023,
                            ClienteId = 103,
                            Data = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1630m,
                            Tipo = "LCI",
                            Valor = 10000m
                        },
                        new
                        {
                            Id = 1024,
                            ClienteId = 103,
                            Data = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1720m,
                            Tipo = "LCI",
                            Valor = 15000m
                        },
                        new
                        {
                            Id = 1025,
                            ClienteId = 103,
                            Data = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1850m,
                            Tipo = "Tesouro",
                            Valor = 100m
                        },
                        new
                        {
                            Id = 1026,
                            ClienteId = 103,
                            Data = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.1980m,
                            Tipo = "Tesouro",
                            Valor = 200m
                        },
                        new
                        {
                            Id = 1027,
                            ClienteId = 103,
                            Data = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rentabilidade = 0.2150m,
                            Tipo = "Tesouro",
                            Valor = 500m
                        });
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.PerfilRisco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PerfisRisco", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Baixa movimentação e foco em liquidez.",
                            Nome = "Conservador"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Equilíbrio entre liquidez e rentabilidade.",
                            Nome = "Moderado"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Busca por alta rentabilidade assumindo maior risco.",
                            Nome = "Agressivo"
                        });
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.ProdutoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Liquidez")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaxPrazoMeses")
                        .HasColumnType("int");

                    b.Property<decimal>("MinValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Rentabilidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProdutosInvestimento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 24,
                            MinValor = 1000m,
                            Nome = "CDB Banco Caixa",
                            Rentabilidade = 0.1125m,
                            Risco = "Baixo",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 2,
                            Liquidez = "D+90",
                            MaxPrazoMeses = 36,
                            MinValor = 5000m,
                            Nome = "LCI Caixa Imobiliário",
                            Rentabilidade = 0.092m,
                            Risco = "Baixo",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 3,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 48,
                            MinValor = 50m,
                            Nome = "Tesouro Selic 2027",
                            Rentabilidade = 0.1035m,
                            Risco = "Baixo",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 4,
                            Liquidez = "D+15",
                            MaxPrazoMeses = 36,
                            MinValor = 2000m,
                            Nome = "CDB Caixa Performance",
                            Rentabilidade = 0.132m,
                            Risco = "Moderado",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 5,
                            Liquidez = "D+120",
                            MaxPrazoMeses = 48,
                            MinValor = 7000m,
                            Nome = "LCI Caixa Desenvolvimento",
                            Rentabilidade = 0.115m,
                            Risco = "Moderado",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 6,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 60,
                            MinValor = 100m,
                            Nome = "Tesouro Prefixado 2029",
                            Rentabilidade = 0.145m,
                            Risco = "Moderado",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 7,
                            Liquidez = "D+30",
                            MaxPrazoMeses = 60,
                            MinValor = 1000m,
                            Nome = "CDB Retorno Turbo XPTO",
                            Rentabilidade = 0.165m,
                            Risco = "Alto",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 8,
                            Liquidez = "D+180",
                            MaxPrazoMeses = 72,
                            MinValor = 8000m,
                            Nome = "LCI FlexMax Corporativa",
                            Rentabilidade = 0.152m,
                            Risco = "Alto",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 9,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 120,
                            MinValor = 100m,
                            Nome = "Tesouro Prefixado 2035 Alta Volatilidade",
                            Rentabilidade = 0.185m,
                            Risco = "Alto",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 10,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 36,
                            MinValor = 2000m,
                            Nome = "CDB Caixa Estabilidade",
                            Rentabilidade = 0.118m,
                            Risco = "Baixo",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 11,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 48,
                            MinValor = 3000m,
                            Nome = "CDB Caixa Conservador Plus",
                            Rentabilidade = 0.121m,
                            Risco = "Baixo",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 12,
                            Liquidez = "D+120",
                            MaxPrazoMeses = 48,
                            MinValor = 6000m,
                            Nome = "LCI Caixa Habitação Popular",
                            Rentabilidade = 0.097m,
                            Risco = "Baixo",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 13,
                            Liquidez = "D+180",
                            MaxPrazoMeses = 60,
                            MinValor = 8000m,
                            Nome = "LCI Caixa Infraestrutura Residencial",
                            Rentabilidade = 0.101m,
                            Risco = "Baixo",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 14,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 60,
                            MinValor = 100m,
                            Nome = "Tesouro Selic 2029",
                            Rentabilidade = 0.108m,
                            Risco = "Baixo",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 15,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 72,
                            MinValor = 200m,
                            Nome = "Tesouro Selic 2031",
                            Rentabilidade = 0.112m,
                            Risco = "Baixo",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 16,
                            Liquidez = "D+30",
                            MaxPrazoMeses = 48,
                            MinValor = 3000m,
                            Nome = "CDB Caixa Dinâmico",
                            Rentabilidade = 0.138m,
                            Risco = "Moderado",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 17,
                            Liquidez = "D+60",
                            MaxPrazoMeses = 60,
                            MinValor = 4000m,
                            Nome = "CDB Caixa Evolução",
                            Rentabilidade = 0.143m,
                            Risco = "Moderado",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 18,
                            Liquidez = "D+150",
                            MaxPrazoMeses = 60,
                            MinValor = 9000m,
                            Nome = "LCI Caixa Corporativa",
                            Rentabilidade = 0.123m,
                            Risco = "Moderado",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 19,
                            Liquidez = "D+180",
                            MaxPrazoMeses = 72,
                            MinValor = 12000m,
                            Nome = "LCI Caixa Premium",
                            Rentabilidade = 0.129m,
                            Risco = "Moderado",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 20,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 72,
                            MinValor = 150m,
                            Nome = "Tesouro Prefixado 2031",
                            Rentabilidade = 0.152m,
                            Risco = "Moderado",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 21,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 96,
                            MinValor = 200m,
                            Nome = "Tesouro IPCA+ 2035 Moderado",
                            Rentabilidade = 0.158m,
                            Risco = "Moderado",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 22,
                            Liquidez = "D+45",
                            MaxPrazoMeses = 72,
                            MinValor = 2000m,
                            Nome = "CDB Potencial Max",
                            Rentabilidade = 0.175m,
                            Risco = "Alto",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 23,
                            Liquidez = "D+90",
                            MaxPrazoMeses = 96,
                            MinValor = 4000m,
                            Nome = "CDB Renda Turbo",
                            Rentabilidade = 0.188m,
                            Risco = "Alto",
                            Tipo = "CDB"
                        },
                        new
                        {
                            Id = 24,
                            Liquidez = "D+240",
                            MaxPrazoMeses = 84,
                            MinValor = 10000m,
                            Nome = "LCI Caixa MaxInvest",
                            Rentabilidade = 0.163m,
                            Risco = "Alto",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 25,
                            Liquidez = "D+360",
                            MaxPrazoMeses = 96,
                            MinValor = 15000m,
                            Nome = "LCI Caixa HighYield",
                            Rentabilidade = 0.172m,
                            Risco = "Alto",
                            Tipo = "LCI"
                        },
                        new
                        {
                            Id = 26,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 144,
                            MinValor = 200m,
                            Nome = "Tesouro Prefixado 2040 HighVol",
                            Rentabilidade = 0.198m,
                            Risco = "Alto",
                            Tipo = "Tesouro"
                        },
                        new
                        {
                            Id = 27,
                            Liquidez = "D+1",
                            MaxPrazoMeses = 180,
                            MinValor = 500m,
                            Nome = "Tesouro IPCA+ 2045 HighRisk",
                            Rentabilidade = 0.215m,
                            Risco = "Alto",
                            Tipo = "Tesouro"
                        });
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoInvestimentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentabilidadeEfetiva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInvestido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoInvestimentoId");

                    b.HasIndex("ClienteId", "DataSimulacao");

                    b.ToTable("Simulacoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3001,
                            ClienteId = 101,
                            DataSimulacao = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrazoMeses = 24,
                            ProdutoInvestimentoId = 1,
                            RentabilidadeEfetiva = 0.1125m,
                            ValorFinal = 2225m,
                            ValorInvestido = 2000m
                        },
                        new
                        {
                            Id = 3002,
                            ClienteId = 101,
                            DataSimulacao = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrazoMeses = 12,
                            ProdutoInvestimentoId = 3,
                            RentabilidadeEfetiva = 0.11m,
                            ValorFinal = 1110m,
                            ValorInvestido = 1000m
                        },
                        new
                        {
                            Id = 3003,
                            ClienteId = 101,
                            DataSimulacao = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrazoMeses = 18,
                            ProdutoInvestimentoId = 12,
                            RentabilidadeEfetiva = 0.09m,
                            ValorFinal = 5450m,
                            ValorInvestido = 5000m
                        },
                        new
                        {
                            Id = 3004,
                            ClienteId = 102,
                            DataSimulacao = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrazoMeses = 18,
                            ProdutoInvestimentoId = 4,
                            RentabilidadeEfetiva = 0.14m,
                            ValorFinal = 3420m,
                            ValorInvestido = 3000m
                        },
                        new
                        {
                            Id = 3005,
                            ClienteId = 102,
                            DataSimulacao = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrazoMeses = 24,
                            ProdutoInvestimentoId = 18,
                            RentabilidadeEfetiva = 0.14m,
                            ValorFinal = 7980m,
                            ValorInvestido = 7000m
                        },
                        new
                        {
                            Id = 3006,
                            ClienteId = 102,
                            DataSimulacao = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrazoMeses = 24,
                            ProdutoInvestimentoId = 21,
                            RentabilidadeEfetiva = 0.18m,
                            ValorFinal = 2360m,
                            ValorInvestido = 2000m
                        },
                        new
                        {
                            Id = 3007,
                            ClienteId = 103,
                            DataSimulacao = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrazoMeses = 12,
                            ProdutoInvestimentoId = 7,
                            RentabilidadeEfetiva = 0.19m,
                            ValorFinal = 4760m,
                            ValorInvestido = 4000m
                        },
                        new
                        {
                            Id = 3008,
                            ClienteId = 103,
                            DataSimulacao = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrazoMeses = 18,
                            ProdutoInvestimentoId = 24,
                            RentabilidadeEfetiva = 0.19m,
                            ValorFinal = 9520m,
                            ValorInvestido = 8000m
                        },
                        new
                        {
                            Id = 3009,
                            ClienteId = 103,
                            DataSimulacao = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrazoMeses = 24,
                            ProdutoInvestimentoId = 27,
                            RentabilidadeEfetiva = 0.24m,
                            ValorFinal = 6200m,
                            ValorInvestido = 5000m
                        });
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.TelemetriaServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantidadeChamadas")
                        .HasColumnType("int");

                    b.Property<int>("TempoMedioRespostaMs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomeServico");

                    b.ToTable("TelemetriaServicos", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("InvestFlowCaixa.Domain.Entities.PerfilRisco", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.HistoricoInvestimento", b =>
                {
                    b.HasOne("InvestFlowCaixa.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Historico")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Simulacao", b =>
                {
                    b.HasOne("InvestFlowCaixa.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Simulacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestFlowCaixa.Domain.Entities.ProdutoInvestimento", "ProdutoInvestimento")
                        .WithMany()
                        .HasForeignKey("ProdutoInvestimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ProdutoInvestimento");
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("Simulacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
