// <auto-generated />
using System;
using InvestFlowCaixa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestFlowCaixa.Infrastructure.Migrations
{
    [DbContext(typeof(InvestimentosDbContext))]
    [Migration("20251114221749_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FrequenciaMovimentacoes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PreferenciaLiquidez")
                        .HasColumnType("int");

                    b.Property<int>("PreferenciaRentabilidade")
                        .HasColumnType("int");

                    b.Property<decimal>("RendaMensal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.HistoricoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rentabilidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("HistoricoInvestimentos", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.PerfilRisco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PontuacaoMax")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PerfisRisco", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.ProdutoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Liquidez")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaxPrazoMeses")
                        .HasColumnType("int");

                    b.Property<decimal>("MinValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Rentabilidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProdutosInvestimento", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoInvestimentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentabilidadeEfetiva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInvestido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoInvestimentoId");

                    b.HasIndex("ClienteId", "DataSimulacao");

                    b.ToTable("Simulacoes", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.TelemetriaServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantidadeChamadas")
                        .HasColumnType("int");

                    b.Property<int>("TempoMedioRespostaMs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomeServico");

                    b.ToTable("TelemetriaServicos", (string)null);
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.HistoricoInvestimento", b =>
                {
                    b.HasOne("InvestFlowCaixa.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Historico")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Simulacao", b =>
                {
                    b.HasOne("InvestFlowCaixa.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Simulacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestFlowCaixa.Domain.Entities.ProdutoInvestimento", "ProdutoInvestimento")
                        .WithMany()
                        .HasForeignKey("ProdutoInvestimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ProdutoInvestimento");
                });

            modelBuilder.Entity("InvestFlowCaixa.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("Simulacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
